services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FAL_KEY: ${FAL_KEY}
      S3_ENDPOINT: https://s3.henrikkvamme.no
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: youtube-voice-cloner