[variables]
# Set Go module path
GO111MODULE = "on"
CGO_ENABLED = "0"
# Ensure binaries are in PATH
PATH = "/usr/local/bin:/usr/bin:/bin"
# Set timezone and locale
TZ = "UTC"
DEBIAN_FRONTEND = "noninteractive"
# SSL configuration for Python/yt-dlp
SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt"
REQUESTS_CA_BUNDLE = "/etc/ssl/certs/ca-certificates.crt"

[phases.setup]
nixPkgs = ["...", "go", "nodejs"]

[phases.install]
cmds = [
  "go mod download",
  "go install github.com/a-h/templ/cmd/templ@latest",
  "npm install"
]

[phases.build]
cmds = [
  "/root/go/bin/templ generate",
  "npx tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css",
  "go build -o out ./cmd/api"
]

[start]
cmd = "export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends curl python3 python3-certifi python3-urllib3 xz-utils tzdata locales ca-certificates && echo 'UTC' > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata && update-ca-certificates && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp && curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o /tmp/ffmpeg.tar.xz && tar -xf /tmp/ffmpeg.tar.xz -C /tmp && mv /tmp/ffmpeg-*-static/ffmpeg /usr/local/bin/ffmpeg && chmod +x /usr/local/bin/ffmpeg && rm -rf /tmp/ffmpeg* && ./out"