[variables]
# Set Go module path
GO111MODULE = "on"
CGO_ENABLED = "0"
# Ensure binaries are in PATH
PATH = "/usr/local/bin:/usr/bin:/bin"

[phases.setup]
nixPkgs = ["...", "go", "nodejs"]
cmds = [
  "apt-get update",
  "apt-get install -y --no-install-recommends ffmpeg curl",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod +x /usr/local/bin/yt-dlp",
  "which ffmpeg",
  "which yt-dlp",
  "ffmpeg -version | head -n 1",
  "yt-dlp --version"
]

[phases.install]
cmds = [
  "go mod download",
  "go install github.com/a-h/templ/cmd/templ@latest",
  "npm install"
]

[phases.build]
cmds = [
  "/root/go/bin/templ generate",
  "npx tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css",
  "go build -o out ./cmd/api"
]

[start]
cmd = "./out"