[variables]
# Set Go module path
GO111MODULE = "on"
CGO_ENABLED = "0"

[phases.setup]
nixPkgs = ["...", "go", "nodejs"]

[phases.install]
cmds = [
  "go mod download",
  "go install github.com/a-h/templ/cmd/templ@latest",
  "npm install",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod +x /usr/local/bin/yt-dlp",
  "apt-get update && apt-get install -y ffmpeg"
]

[phases.build]
cmds = [
  "/root/go/bin/templ generate",
  "npx tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css",
  "go build -o out ./cmd/api"
]

[start]
cmd = "./out"