// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/henrik392/youtube-voice-go/cmd/web/components"

func MainPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"px-4 py-8 mx-auto max-w-4xl\"><div class=\"mb-12 text-center\"><h1 class=\"mb-4 text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl\">Clone Any Voice with AI</h1><p class=\"mx-auto max-w-2xl text-xl text-gray-600\">Transform any audio into custom AI-generated speech. Choose your audio source and let our AI clone the voice.</p></div><div class=\"mx-auto max-w-3xl\"><form id=\"voice-form\" hx-post=\"/generate-voice-enhanced\" hx-target=\"#audio-player\" hx-swap=\"outerHTML\" hx-indicator=\"#voice-generation-loading\" enctype=\"multipart/form-data\"><!-- Audio Input Mode Selector -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.AudioInputModeSelector().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Dynamic Audio Input Container --><div id=\"audio-input-container\" class=\"mb-8\"><!-- This will be populated by JavaScript based on selected mode --></div><!-- Text to Speech Section --><div class=\"text-start\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TextAreaToSpeech().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Tips Section --><div class=\"p-4 mt-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border border-blue-200\"><div class=\"flex items-start space-x-3\"><svg class=\"flex-shrink-0 mt-0.5 w-5 h-5 text-blue-500\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path fill-rule=\"evenodd\" d=\"M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z\" clip-rule=\"evenodd\"></path></svg><div class=\"text-sm text-blue-800\"><p class=\"mb-2 font-semibold\">Tips for best results:</p><ul class=\"space-y-1 text-blue-700\"><li>• Use at least 10 seconds of clean, clear audio</li><li>• Avoid background noise and music</li><li>• Single speaker works better than multiple voices</li><li>• Generation may take 20-30 seconds</li></ul></div></div></div></div><div class=\"flex flex-col justify-center items-center mt-8 space-y-4 w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SubmitButton().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.AudioPlayer("", "").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></form></div><!-- Loading Animation -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.LoadingAnimation().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><script>\n\t\t\t// Alpine.js Store Setup\n\t\t\tdocument.addEventListener('alpine:init', () => {\n\t\t\t\tAlpine.store('voiceClone', {\n\t\t\t\t\t// State\n\t\t\t\t\taudioMode: 'url',\n\t\t\t\t\ttextValid: false,\n\t\t\t\t\taudioInputValid: false,\n\n\t\t\t\t\t// Computed\n\t\t\t\t\tget isFormValid() {\n\t\t\t\t\t\treturn this.textValid && this.audioInputValid;\n\t\t\t\t\t},\n\n\t\t\t\t\t// Actions\n\t\t\t\t\tsetAudioMode(mode) {\n\t\t\t\t\t\tthis.audioMode = mode;\n\t\t\t\t\t\tthis.audioInputValid = false; // Reset validation when mode changes\n\t\t\t\t\t},\n\n\t\t\t\t\tvalidateText(text) {\n\t\t\t\t\t\tthis.textValid = text.length > 0 && text.length <= 500;\n\t\t\t\t\t},\n\n\t\t\t\t\tvalidateAudioInput(isValid) {\n\t\t\t\t\t\tthis.audioInputValid = isValid;\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t});\n\n\t\t\t// Load default URL input on page load\n\t\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\t\t// Load URL input by default\n\t\t\t\thtmx.ajax('POST', '/validate-url', {target: '#audio-input-container'});\n\t\t\t});\n\n\t\t\t// Add audio mode to request parameters and debug\n\t\t\tdocument.addEventListener('htmx:configRequest', function(evt) {\n\t\t\t\tconst form = evt.detail.elt;\n\t\t\t\tif (form.id === 'voice-form') {\n\t\t\t\t\tconsole.log('HTMX request starting');\n\t\t\t\t\tconst audioMode = Alpine.store('voiceClone').audioMode;\n\t\t\t\t\tevt.detail.parameters['audio-mode'] = audioMode;\n\t\t\t\t}\n\t\t\t});\n\n\t\t\t// Debug HTMX events\n\t\t\tdocument.addEventListener('htmx:beforeRequest', function(evt) {\n\t\t\t\tconsole.log('Before request:', evt.detail);\n\t\t\t});\n\n\t\t\tdocument.addEventListener('htmx:afterRequest', function(evt) {\n\t\t\t\tconsole.log('After request:', evt.detail);\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
