// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TextAreaToSpeech() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mt-6\" x-data=\"{ \n\t\ttext: '', \n\t\tget charCount() { return this.text.length; },\n\t\tget isOverLimit() { return this.charCount >= 500; },\n\t\tget isNearLimit() { return this.charCount >= 450; }\n\t}\" x-effect=\"$store.voiceClone.validateText(text)\"><div class=\"flex justify-between items-center mb-1\"><label for=\"text\" class=\"block pl-4 text-sm font-bold leading-6 text-gray-900\">Text to Speech</label><div class=\"text-sm text-gray-500 mr-4\"><span x-text=\"charCount\" :class=\"isOverLimit ? 'text-red-600 font-semibold' : \n\t\t\t\t\t\t\t  isNearLimit ? 'text-amber-600 font-semibold' : \n\t\t\t\t\t\t\t  'text-gray-500'\">0</span>/500</div></div><div class=\"relative\"><textarea name=\"text\" id=\"text\" maxlength=\"500\" x-model=\"text\" :class=\"isOverLimit ? 'ring-red-300 focus:ring-red-500' : \n\t\t\t\t\t\tisNearLimit ? 'ring-amber-300 focus:ring-amber-500' : \n\t\t\t\t\t\t'ring-gray-300 focus:ring-indigo-600'\" class=\"block w-full rounded-md border-0 mt-1 pb-8 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6\" placeholder=\"Enter text to convert to speech (max 500 characters)...\"></textarea><div x-show=\"isOverLimit\" x-transition class=\"mt-2 p-3 bg-amber-50 border border-amber-200 rounded-md\"><div class=\"flex items-center\"><svg class=\"w-5 h-5 text-amber-400 mr-2\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path fill-rule=\"evenodd\" d=\"M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z\" clip-rule=\"evenodd\"></path></svg> <span class=\"text-amber-800 text-sm font-medium\">Character limit reached! Please keep your text under 500 characters for optimal voice quality.</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
